#### general settings
name: indoor-sdsd
use_tb_logger: true
model: video_base
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: indoor
    mode: video_samesize
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: path_to_dataset/indoor_np/GT
    dataroot_LQ: path_to_dataset/indoor_np/input
    train_size: [960, 512]
    cache_keys: ~
    cache_data: true
    padding: new_info
    testing_dir: pair13,pair15,pair21,pair23,pair31,pair33,pair50,pair52,pair58,pair60,pair68,pair70


    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 32
    GT_size: 128     # size you want to crop out as input sample.
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: video_samesize
    dataroot_GT: path_to_dataset/indoor_np/GT
    dataroot_LQ: path_to_dataset/indoor_np/input
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]

#### network structures
network_G:
  which_model_G: denoise_illumination_enhance
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: true
  HR_in: true
  w_TSA: true

#### path
path:
  root: ./
  ## e.g., if you want to resume the training from iteration of 140000, you should write pretrain_model_G and resume_state like this.
  ## pretrain_model_G: experiments/indoor-sdsd/models/140000_G.pth
  strict_load: false
  ## resume_state: experiments/indoor-sdsd/training_state/140000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 2318

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
